### ISSUE TITLE
Font error when using mtpro2-pacth

### ISSUE THREAD

**Issue by Ice0cean** [RuixiZhang42/font-pairing-guide#1]
I found that when I use mtpro2-patch in my document, the font error was thrown out

>   Font \nullfont has only 7 fontdimen parameters

Can you fix it?

I use texlive and updated it recently. 

Best regards

**Comment by RuixiZhang42** [comment]
Sorry for the late reply. Could you provide a short example code to illustrate the problem?

Since I can compile my old documents just fine, I can only take a guess at this moment. The error probably has something to do with my various attempts to “centering the strut used in `array` environment”. But without an example to produce the error you encountered, it’s impossible to pinpoint the bug.

**Comment by RuixiZhang42** [comment]
There are pieces of code in `mtpro2-patch.tex` hooked into `\AtBeginDocument`, which are supposed to take effect *after* `amsmath`’s hook. But I think the new hook management system messes up this crucial order (this new system was introduced by the 2020-10-01 release of LaTeX2e). My patch code was probably executed *before* the `amsmath` code, which probably then leads to your error.

If my guess were true, this would be very frustrating. IMO the particular `amsmath` code was completely redundant and useless (and now it has become *harmful*). I reported this almost exactly one year ago to the LaTeX3 team, but no progress has been made. See https://github.com/latex3/latex2e/issues/207

A quick fix is to comment out (or remove) the following lines from `mtpro2-patch.tex`:
https://github.com/RuixiZhang42/font-pairing-guide/blob/22f5146db077d90d762491a0af1cd819dfd65915/mtpro2-patch.tex#L687-L696
This will make that `Font \nullfont has only 7 fontdimen parameters` error go away. But then the `gathered`, `aligned` environments won’t be properly vertically centered. I’ll need to think of a more comprehensive solution…

**Comment by RuixiZhang42** [comment]
Alternatively, you can try
```latex
...
\usepackage[<options>]{mtpro2}
\input{mtpro2-patch}

\ifx\DeclareHookRule\undefined\else
  \DeclareHookRule{begindocument}{amsmath}{after}{top-level}
\fi
...
```
