### ISSUE TITLE
Request: adjust the width of the reduction sign symbol

### ISSUE THREAD

**Issue by poorich** [RuixiZhang42/font-pairing-guide#3]
\[
    \begin{cases}
    a+a+a+a+a+a+a+a+a+a+a+a \\
    a-a-a-a-a-a-a-a-a-a-a-a
    \end{cases}
    \]
The width of `+` and `-` is different, it is uncomfortable

**Comment by poorich** [comment]
\[
\begin{cases}
a+a+a+a+a+a+a+a+a+a+a+a \\
a-a-a-a-a-a-a-a-a-a-a-a
\end{cases}
\]
The width of `+` and `-` is different, it is uncomfortable

**Comment by RuixiZhang42** [comment]
This is a problem of *MathTime Pro&nbsp;2* (the font) itself. In the math symbol font `mt2syt` (display and text styles), the plus sign is 836 units wide, while the minus sign is 724 units wide. The same issues are in `mt2sys` (script style, plus is 908, while minus is 796) and in `mt2syf` (scriptscript style, plus is 1076, while minus is 948). Therefore, these are **font design flaws**.

My patch file `mtpro2-patch.tex` already provides a solution at the macro/command level. You can fix these issues by writing `\tabularbin` for **tabular bin**ary operators (and `\tabularrel` for **tabular rel**ation symbols).
```latex
\documentclass{article}
\usepackage[lite]{mtpro2}
\input{mtpro2-patch} % defines \tabularbin and \tabularrel, each taking one mandatory argument
\begin{document}
\[
\begin{array}{cc}
a\tabularbin+a\tabularbin+a & b\tabularrel=   b\tabularrel=   b\\
a\tabularbin-a\tabularbin-a & b\tabularrel\le b\tabularrel\le b
\end{array}
\]
\end{document}
```

**Comment by poorich** [comment]
Your code is quite esoteric, but interesting.
Can we replace the `plus +` and `subtraction -` to the corresponding symbols in `newtxmath`?
If choose option `lite`, we can also consider replacing some text fonts of math mode

**Comment by RuixiZhang42** [comment]
`newtxmath` has the same design flaws. The details of these issues and some explanations of my code can be read here: https://tex.stackexchange.com/q/364147
